
package ifneeded osys::rfg 1.0.0  [list source [file join $dir rfg.tm]]
package ifneeded osys::rfg::generator::xmlgenerator 1.0.0 [list source [file join $dir generator-xml XMLGenerator.tm]]
package ifneeded osys::rfg::generator::htmlbrowser 1.0.0 [list source [file join $dir generator-htmlbrowser htmlbrowser.tm]]
package ifneeded osys::rfg::generator::rfsbackport 1.0.0 [list source [file join $dir generator-rfsbackport rfsbackport.tm]]
package ifneeded osys::rfg::generator::verilog 1.0.0 [list source [file join $dir generator-verilog VerilogGenerator.tm]]
package ifneeded osys::rfg::generator::rfgheader 1.0.0 [list source [file join $dir generator-rfgheader rfgheader.tm]]
package ifneeded osys::rfg::generator::wrapper 1.0.0 [list source [file join $dir generator-wrapper WrapperGenerator.tm]]
package ifneeded osys::rfg::address 1.0.0 [list source [file join $dir address address.tm]]
package ifneeded osys::rfg::trigger 1.0.0 [list source [file join $dir trigger trigger.tm]]
package ifneeded osys::rfg::generator::egenerator 1.0.0 [list source [file join $dir generator-e eGenerator.tm]]
package ifneeded osys::rfg::generator::sv 1.0.0 [list source [file join $dir generator-sv sv.tm]]

package ifneeded HelperFunctions 1.0.0 [list source [file join $dir generator-verilog HelperFunctions.tm]]
package ifneeded osys::generator 1.0.0 [list source [file join $dir generator.tm]]
