/* auto generated by RFG */
/* address map
test: base[3:3] 0 size: 8

*/
/* instantiation template
reg_hrw_srw_counter reg_hrw_srw_counter_I (
	.res_n(),
	.clk(),
	.address(),
	.read_data(),
	.invalid_address(),
	.access_complete(),
	.read_en(),
	.write_en(),
	.write_data(),
	.test_test_field_next(),
	.test_test_field(),
	.test_test_field_wen(),
	.test_test_field_countup()
);
*/
module reg_hrw_srw_counter
(
	input wire clk,
	input wire res_n,
	// Software Interface
    input wire[3:3] address,
	output reg[31:0] read_data,
	output reg invalid_address,
	output reg access_complete,
	input wire read_en,
	input wire write_en,
	input wire[31:0] write_data,
	// Hardware Interface
	input wire[31:0] test_test_field_next,
	output wire[31:0] test_test_field,
	input wire test_test_field_wen,
	input wire test_test_field_countup
);

	reg test_test_field_load_enable;
	reg[31:0] test_test_field_load_value;

	counter48 #(
		.DATASIZE(32)
	) test_test_field_I (
		.clk(clk),
		.res_n(res_n),
		.increment(test_test_field_countup),
		.load(test_test_field_load_value),
		.load_enable(test_test_field_load_enable),
		.value(test_test_field)
	);

	/* register test */
	always @(posedge clk)
	begin
		if (!res_n)
		begin
			test_test_field_load_enable <= 1'b0;
		end
		else
		begin

			if((address[3:3]== 0) && write_en)
			begin
				test_test_field_load_enable <= 1'b1;
				test_test_field_load_value <= write_data[31:0];
			end
			else if(test_test_field_wen)
			begin
				test_test_field_load_value <= test_test_field_next;
				test_test_field_load_enable <= 1'b1;
			end
			else
			begin
				test_test_field_load_enable <= 1'b0;
				test_test_field_load_value <= 32'b0;
			end
		end
	end

	always @(posedge clk)
	begin
		if (!res_n)
		begin
			invalid_address <= 1'b0;
			access_complete <= 1'b0;
		end
		else
		begin

			casex(address[3:3])
				1'h0:
				begin
					read_data[31:0] <= test_test_field;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en;
				end
				default:
				begin
					invalid_address <= read_en || write_en;
					access_complete <= read_en || write_en;
				end		
			endcase
		end
	end
endmodule
