

/* auto generated by RFG */
/* address map
RAM: base: 0x256 size: 256
RAM: base: 0x768 size: 256
RAM: base: 0x1792 size: 256

*/
/* instantiation template
absAddrRAM absAddrRAM_I (
	.res_n(),
	.clk(),
	.address(),
	.read_data(),
	.invalid_address(),
	.access_complete(),
	.read_en(),
	.write_en(),
	.write_data(),
	.RAM_addr(),
	.RAM_ren(),
	.RAM_rdata(),
	.RAM_wen(),
	.RAM_wdata(),
	.RAM_addr(),
	.RAM_ren(),
	.RAM_rdata(),
	.RAM_wen(),
	.RAM_wdata(),
	.RAM_addr(),
	.RAM_ren(),
	.RAM_rdata(),
	.RAM_wen(),
	.RAM_wdata()
);
*/
module absAddrRAM
(
	///\defgroup sys
	///@{ 
	input wire res_n,
	input wire clk,
	///}@ 
	///\defgroup rw_if
	///@{ 
	input wire[10:3] address,
	output reg[63:0] read_data,
	output reg invalid_address,
	output reg access_complete,
	input wire read_en,
	input wire write_en,
	input wire[63:0] write_data,
	///}@ 
	input wire[4:0] RAM_addr,
	input wire RAM_ren,
	output wire[15:0] RAM_rdata,
	input wire RAM_wen,
	input wire[15:0] RAM_wdata,
	input wire[4:0] RAM_addr,
	input wire RAM_ren,
	output wire[15:0] RAM_rdata,
	input wire RAM_wen,
	input wire[15:0] RAM_wdata,
	input wire[4:0] RAM_addr,
	input wire RAM_ren,
	output wire[15:0] RAM_rdata,
	input wire RAM_wen,
	input wire[15:0] RAM_wdata

);

	reg[4:0] RAM_rf_addr;
	reg RAM_rf_ren;
	wire[15:0] RAM_rf_rdata;
	reg RAM_rf_wen;
	reg[15:0] RAM_rf_wdata;
	reg read_en_dly0;
	reg read_en_dly1;
	reg read_en_dly2;
	reg[4:0] RAM_rf_addr;
	reg RAM_rf_ren;
	wire[15:0] RAM_rf_rdata;
	reg RAM_rf_wen;
	reg[15:0] RAM_rf_wdata;
	reg read_en_dly0;
	reg read_en_dly1;
	reg read_en_dly2;
	reg[4:0] RAM_rf_addr;
	reg RAM_rf_ren;
	wire[15:0] RAM_rf_rdata;
	reg RAM_rf_wen;
	reg[15:0] RAM_rf_wdata;
	reg read_en_dly0;
	reg read_en_dly1;
	reg read_en_dly2;

	ram_2rw_1c #(
		.DATASIZE(16),
		.ADDRSIZE(5),
		.PIPELINED(0)
	) RAM (
		.clk(clk),
		.wen_a(RAM_rf_wen),
		.ren_a(RAM_rf_ren),
		.addr_a(RAM_rf_addr),
		.wdata_a(RAM_rf_wdata),
		.rdata_a(RAM_rf_rdata),
		.wen_b(RAM_wen),
		.ren_b(RAM_ren),
		.addr_b(RAM_addr),
		.wdata_b(RAM_wdata),
		.rdata_b(RAM_rdata)
	);

	ram_2rw_1c #(
		.DATASIZE(16),
		.ADDRSIZE(5),
		.PIPELINED(0)
	) RAM (
		.clk(clk),
		.wen_a(RAM_rf_wen),
		.ren_a(RAM_rf_ren),
		.addr_a(RAM_rf_addr),
		.wdata_a(RAM_rf_wdata),
		.rdata_a(RAM_rf_rdata),
		.wen_b(RAM_wen),
		.ren_b(RAM_ren),
		.addr_b(RAM_addr),
		.wdata_b(RAM_wdata),
		.rdata_b(RAM_rdata)
	);

	ram_2rw_1c #(
		.DATASIZE(16),
		.ADDRSIZE(5),
		.PIPELINED(0)
	) RAM (
		.clk(clk),
		.wen_a(RAM_rf_wen),
		.ren_a(RAM_rf_ren),
		.addr_a(RAM_rf_addr),
		.wdata_a(RAM_rf_wdata),
		.rdata_a(RAM_rf_rdata),
		.wen_b(RAM_wen),
		.ren_b(RAM_ren),
		.addr_b(RAM_addr),
		.wdata_b(RAM_wdata),
		.rdata_b(RAM_rdata)
	);


	/* RamBlock RAM */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			`ifdef ASIC
			RAM_rf_addr <= 5'b0;
			RAM_rf_wdata  <= 16'b0;
			`endif
			RAM_rf_wen <= 1'b0;
			RAM_rf_ren <= 1'b0;
		end
		else
		begin
			if (address[10:8] == 1)
			begin
				RAM_rf_addr <= address[7:3];
				RAM_rf_wdata <= write_data[15:0];
				RAM_rf_wen <= write_en;
				RAM_rf_ren <= read_en;
			end
		end
	end

	/* RamBlock RAM */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			`ifdef ASIC
			RAM_rf_addr <= 5'b0;
			RAM_rf_wdata  <= 16'b0;
			`endif
			RAM_rf_wen <= 1'b0;
			RAM_rf_ren <= 1'b0;
		end
		else
		begin
			if (address[10:8] == 3)
			begin
				RAM_rf_addr <= address[7:3];
				RAM_rf_wdata <= write_data[15:0];
				RAM_rf_wen <= write_en;
				RAM_rf_ren <= read_en;
			end
		end
	end

	/* RamBlock RAM */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			`ifdef ASIC
			RAM_rf_addr <= 5'b0;
			RAM_rf_wdata  <= 16'b0;
			`endif
			RAM_rf_wen <= 1'b0;
			RAM_rf_ren <= 1'b0;
		end
		else
		begin
			if (address[10:8] == 7)
			begin
				RAM_rf_addr <= address[7:3];
				RAM_rf_wdata <= write_data[15:0];
				RAM_rf_wen <= write_en;
				RAM_rf_ren <= read_en;
			end
		end
	end


	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			invalid_address <= 1'b0;
			access_complete <= 1'b0;
			`ifdef ASIC
			read_data   <= 64'b0;
			`endif

			read_en_dly0 <= 1'b0;
			read_en_dly1 <= 1'b0;
			read_en_dly2 <= 1'b0;
		end
		else
		begin
			read_en_dly0 <= read_en;
			read_en_dly1 <= read_en_dly0;
			read_en_dly2 <= read_en_dly1;

			casex(address[10:3])
				{3'h1,5'bxxxxx}:
				begin
					read_data[15:0] <= RAM_rf_rdata;
					read_data[63:16] <= 48'b0;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en_dly2;
				end
				{3'h3,5'bxxxxx}:
				begin
					read_data[15:0] <= RAM_rf_rdata;
					read_data[63:16] <= 48'b0;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en_dly2;
				end
				{3'h7,5'bxxxxx}:
				begin
					read_data[15:0] <= RAM_rf_rdata;
					read_data[63:16] <= 48'b0;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en_dly2;
				end
				default:
				begin
					invalid_address <= read_en || write_en;
					access_complete <= read_en || write_en;
				end		
			endcase
		end
	end
endmodule