

/* auto generated by RFG */
/* address map
GPR_Group_GPR: base: 0x0 size: 8
RAM_Group_RAM: base: 0x800 size: 2048
RAM_Group0_RAM: base: 0x1800 size: 2048

*/
/* instantiation template
absAddrRAM absAddrRAM_I (
	.res_n(),
	.clk(),
	.address(),
	.read_data(),
	.invalid_address(),
	.access_complete(),
	.read_en(),
	.write_en(),
	.write_data(),
	.GPR_Group_GPR_GPF_next(),
	.GPR_Group_GPR_GPF(),
	.GPR_Group_GPR_GPF_wen(),
	.GPR_Group_GPR_GPF_written(),
	.RAM_Group_RAM_addr(),
	.RAM_Group_RAM_ren(),
	.RAM_Group_RAM_rdata(),
	.RAM_Group_RAM_wen(),
	.RAM_Group_RAM_wdata(),
	.RAM_Group0_RAM_addr(),
	.RAM_Group0_RAM_ren(),
	.RAM_Group0_RAM_rdata(),
	.RAM_Group0_RAM_wen(),
	.RAM_Group0_RAM_wdata()
);
*/
module absAddrRAM
(
	///\defgroup sys
	///@{ 
	input wire res_n,
	input wire clk,
	///}@ 
	///\defgroup rw_if
	///@{ 
	input wire[13:3] address,
	output reg[63:0] read_data,
	output reg invalid_address,
	output reg access_complete,
	input wire read_en,
	input wire write_en,
	input wire[63:0] write_data,
	///}@ 
	input wire[63:0] GPR_Group_GPR_GPF_next,
	output reg[63:0] GPR_Group_GPR_GPF,
	input wire GPR_Group_GPR_GPF_wen,
	output reg GPR_Group_GPR_GPF_written,
	input wire[7:0] RAM_Group_RAM_addr,
	input wire RAM_Group_RAM_ren,
	output wire[15:0] RAM_Group_RAM_rdata,
	input wire RAM_Group_RAM_wen,
	input wire[15:0] RAM_Group_RAM_wdata,
	input wire[7:0] RAM_Group0_RAM_addr,
	input wire RAM_Group0_RAM_ren,
	output wire[15:0] RAM_Group0_RAM_rdata,
	input wire RAM_Group0_RAM_wen,
	input wire[15:0] RAM_Group0_RAM_wdata

);

	reg[7:0] RAM_Group_RAM_rf_addr;
	reg RAM_Group_RAM_rf_ren;
	wire[15:0] RAM_Group_RAM_rf_rdata;
	reg RAM_Group_RAM_rf_wen;
	reg[15:0] RAM_Group_RAM_rf_wdata;
	reg read_en_dly0;
	reg read_en_dly1;
	reg read_en_dly2;
	reg[7:0] RAM_Group0_RAM_rf_addr;
	reg RAM_Group0_RAM_rf_ren;
	wire[15:0] RAM_Group0_RAM_rf_rdata;
	reg RAM_Group0_RAM_rf_wen;
	reg[15:0] RAM_Group0_RAM_rf_wdata;
	reg read_en_dly0;
	reg read_en_dly1;
	reg read_en_dly2;

	ram_2rw_1c #(
		.DATASIZE(16),
		.ADDRSIZE(8),
		.PIPELINED(0)
	) RAM_Group_RAM (
		.clk(clk),
		.wen_a(RAM_Group_RAM_rf_wen),
		.ren_a(RAM_Group_RAM_rf_ren),
		.addr_a(RAM_Group_RAM_rf_addr),
		.wdata_a(RAM_Group_RAM_rf_wdata),
		.rdata_a(RAM_Group_RAM_rf_rdata),
		.wen_b(RAM_Group_RAM_wen),
		.ren_b(RAM_Group_RAM_ren),
		.addr_b(RAM_Group_RAM_addr),
		.wdata_b(RAM_Group_RAM_wdata),
		.rdata_b(RAM_Group_RAM_rdata)
	);

	ram_2rw_1c #(
		.DATASIZE(16),
		.ADDRSIZE(8),
		.PIPELINED(0)
	) RAM_Group0_RAM (
		.clk(clk),
		.wen_a(RAM_Group0_RAM_rf_wen),
		.ren_a(RAM_Group0_RAM_rf_ren),
		.addr_a(RAM_Group0_RAM_rf_addr),
		.wdata_a(RAM_Group0_RAM_rf_wdata),
		.rdata_a(RAM_Group0_RAM_rf_rdata),
		.wen_b(RAM_Group0_RAM_wen),
		.ren_b(RAM_Group0_RAM_ren),
		.addr_b(RAM_Group0_RAM_addr),
		.wdata_b(RAM_Group0_RAM_wdata),
		.rdata_b(RAM_Group0_RAM_rdata)
	);


	/* register GPR */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			GPR_Group_GPR_GPF <= 64'h0;
			GPR_Group_GPR_GPF_written <= 1'b0;
		end
		else
		begin

			if((address[13:3]== 0) && write_en)
			begin
				GPR_Group_GPR_GPF <= write_data[63:0];
			end
			else if(GPR_Group_GPR_GPF_wen)
			begin
				GPR_Group_GPR_GPF <= GPR_Group_GPR_GPF_next;
			end
			if((address[13:3]== 0) && write_en)
			begin
				GPR_Group_GPR_GPF_written <= 1'b1;
			end
			else
			begin
				GPR_Group_GPR_GPF_written <= 1'b0;
			end

		end
	end

	/* RamBlock RAM_Group_RAM */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			`ifdef ASIC
			RAM_Group_RAM_rf_addr <= 8'b0;
			RAM_Group_RAM_rf_wdata  <= 16'b0;
			`endif
			RAM_Group_RAM_rf_wen <= 1'b0;
			RAM_Group_RAM_rf_ren <= 1'b0;
		end
		else
		begin
			if (address[13:11] == 1)
			begin
				RAM_Group_RAM_rf_addr <= address[10:3];
				RAM_Group_RAM_rf_wdata <= write_data[15:0];
				RAM_Group_RAM_rf_wen <= write_en;
				RAM_Group_RAM_rf_ren <= read_en;
			end
		end
	end

	/* register RAM */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
		end
		else
		begin

		end
	end

	/* RamBlock RAM_Group0_RAM */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			`ifdef ASIC
			RAM_Group0_RAM_rf_addr <= 8'b0;
			RAM_Group0_RAM_rf_wdata  <= 16'b0;
			`endif
			RAM_Group0_RAM_rf_wen <= 1'b0;
			RAM_Group0_RAM_rf_ren <= 1'b0;
		end
		else
		begin
			if (address[13:11] == 3)
			begin
				RAM_Group0_RAM_rf_addr <= address[10:3];
				RAM_Group0_RAM_rf_wdata <= write_data[15:0];
				RAM_Group0_RAM_rf_wen <= write_en;
				RAM_Group0_RAM_rf_ren <= read_en;
			end
		end
	end

	/* register RAM */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
		end
		else
		begin

		end
	end


	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			invalid_address <= 1'b0;
			access_complete <= 1'b0;
			`ifdef ASIC
			read_data   <= 64'b0;
			`endif

			read_en_dly0 <= 1'b0;
			read_en_dly1 <= 1'b0;
			read_en_dly2 <= 1'b0;
		end
		else
		begin
			read_en_dly0 <= read_en;
			read_en_dly1 <= read_en_dly0;
			read_en_dly2 <= read_en_dly1;

			casex(address[13:3])
				11'h0:
				begin
					read_data[63:0] <= GPR_Group_GPR_GPF;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en;
				end
				{3'h1,8'bxxxxxxxx}:
				begin
					read_data[15:0] <= RAM_Group_RAM_rf_rdata;
					read_data[63:16] <= 48'b0;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en_dly2;
				end
				{3'h3,10'bxxxxxxxx}:
				begin
					read_data[15:0] <= RAM_Group0_RAM_rf_rdata;
					read_data[63:16] <= 48'b0;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en_dly2;
				end
				default:
				begin
					invalid_address <= read_en || write_en;
					access_complete <= read_en || write_en;
				end		
			endcase
		end
	end
endmodule