

/* auto generated by RFG */
/* address map
tsc: base: 0x0 size: 8
cnt_rreinit: base: 0x8 size: 8
tsc2: base: 0x10 size: 8
tsc3: base: 0x18 size: 8
tsc4: base: 0x20 size: 8

*/
/* instantiation template
counter_RF counter_RF_I (
	.res_n(),
	.clk(),
	.address(),
	.read_data(),
	.invalid_address(),
	.access_complete(),
	.read_en(),
	.write_en(),
	.write_data(),
	.tsc_cnt_next(),
	.tsc_cnt(),
	.tsc_cnt_wen(),
	.tsc_cnt_countup(),
	.tsc2_cnt_countup(),
	.tsc3_cnt_countup(),
	.tsc4_cnt_next(),
	.tsc4_cnt(),
	.tsc4_cnt_wen(),
	.tsc4_cnt_countup()
);
*/
module counter_RF
(
	///\defgroup sys
	///@{ 
	input wire res_n,
	input wire clk,
	///}@ 
	///\defgroup rw_if
	///@{ 
	input wire[5:3] address,
	output reg[63:0] read_data,
	output reg invalid_address,
	output reg access_complete,
	input wire read_en,
	input wire write_en,
	input wire[63:0] write_data,
	///}@ 
	input wire[47:0] tsc_cnt_next,
	output wire[47:0] tsc_cnt,
	input wire tsc_cnt_wen,
	input wire tsc_cnt_countup,
	input wire tsc2_cnt_countup,
	input wire tsc3_cnt_countup,
	input wire[47:0] tsc4_cnt_next,
	output wire[47:0] tsc4_cnt,
	input wire tsc4_cnt_wen,
	input wire tsc4_cnt_countup

);

	reg tsc_cnt_load_enable;
	reg[47:0] tsc_cnt_load_value;
	reg rreinit;
	wire[47:0] tsc2_cnt;
	reg tsc3_cnt_load_enable;
	reg[47:0] tsc3_cnt_load_value;
	wire[47:0] tsc3_cnt;
	reg tsc4_cnt_load_enable;
	reg[47:0] tsc4_cnt_load_value;

	counter48 #(
		.DATASIZE(48)
	) tsc_cnt_I (
		.clk(clk),
		.res_n(res_n),
		.increment(tsc_cnt_countup),
		.load(tsc_cnt_load_value),
		.load_enable(tsc_cnt_load_enable),
		.value(tsc_cnt)
	);

	counter48 #(
		.DATASIZE(48)
	) tsc2_cnt_I (
		.clk(clk),
		.res_n(res_n),
		.increment(tsc2_cnt_countup),
 		.load(48'b0),
		.load_enable(rreinit),
		.value(tsc2_cnt)
	);

	counter48 #(
		.DATASIZE(48)
	) tsc3_cnt_I (
		.clk(clk),
		.res_n(res_n),
		.increment(tsc3_cnt_countup),
		.load(tsc3_cnt_load_value),
		.load_enable(rreinit || tsc3_cnt_load_enable),
		.value(tsc3_cnt)
	);

	counter48 #(
		.DATASIZE(48)
	) tsc4_cnt_I (
		.clk(clk),
		.res_n(res_n),
		.increment(tsc4_cnt_countup),
		.load(tsc4_cnt_load_value),
		.load_enable(rreinit || tsc4_cnt_load_enable),
		.value(tsc4_cnt)
	);


	/* register tsc */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			tsc_cnt_load_enable <= 1'b0;
		end
		else
		begin

			if((address[5:3]== 0) && write_en)
			begin
				tsc_cnt_load_enable <= 1'b1;
				tsc_cnt_load_value <= write_data[47:0];
			end
			else if(tsc_cnt_wen)
			begin
				tsc_cnt_load_value <= tsc_cnt_next;
				tsc_cnt_load_enable <= 1'b1;
			end
			else
			begin
				tsc_cnt_load_enable <= 1'b0;
				tsc_cnt_load_value <= 48'b0;
			end
		end
	end

	/* register cnt_rreinit */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			rreinit <= 1'b0;
		end
		else
		begin

			if((address[5:3]== 1) && write_en)
			begin
				rreinit <= 1'b1;
			end
			else
			begin
				rreinit <= 1'b0;
			end
		end
	end

	/* register tsc2 */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
		end
		else
		begin

		end
	end

	/* register tsc3 */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			tsc3_cnt_load_enable <= 1'b0;
		end
		else
		begin

			if((address[5:3]== 3) && write_en)
			begin
				tsc3_cnt_load_enable <= 1'b1;
				tsc3_cnt_load_value <= write_data[47:0];
			end
			else
			begin
				tsc3_cnt_load_enable <= 1'b0;
				tsc3_cnt_load_value <= 48'b0;
			end
		end
	end

	/* register tsc4 */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			tsc4_cnt_load_enable <= 1'b0;
		end
		else
		begin

			if((address[5:3]== 4) && write_en)
			begin
				tsc4_cnt_load_enable <= 1'b1;
				tsc4_cnt_load_value <= write_data[47:0];
			end
			else if(tsc4_cnt_wen)
			begin
				tsc4_cnt_load_value <= tsc4_cnt_next;
				tsc4_cnt_load_enable <= 1'b1;
			end
			else
			begin
				tsc4_cnt_load_enable <= 1'b0;
				tsc4_cnt_load_value <= 48'b0;
			end
		end
	end


	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			invalid_address <= 1'b0;
			access_complete <= 1'b0;
			`ifdef ASIC
			read_data   <= 64'b0;
			`endif

		end
		else
		begin

			casex(address[5:3])
				3'h0:
				begin
					read_data[47:0] <= tsc_cnt;
					read_data[63:48] <= 16'b0;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en;
				end
				3'h1:
				begin
					read_data[63:0] <= 64'b0;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en;
				end
				3'h2:
				begin
					read_data[47:0] <= tsc2_cnt;
					read_data[63:48] <= 16'b0;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en;
				end
				3'h3:
				begin
					read_data[47:0] <= tsc3_cnt;
					read_data[63:48] <= 16'b0;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en;
				end
				3'h4:
				begin
					read_data[47:0] <= tsc4_cnt;
					read_data[63:48] <= 16'b0;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en;
				end
				default:
				begin
					invalid_address <= read_en || write_en;
					access_complete <= read_en || write_en;
				end		
			endcase
		end
	end
endmodule