

/* auto generated by RFG */
/* address map
info_rf_TestRAM: base: 0x0 size: 256

*/
/* instantiation template
ramRF ramRF_I (
	.res_n(),
	.clk(),
	.address(),
	.read_data(),
	.invalid_address(),
	.access_complete(),
	.read_en(),
	.write_en(),
	.write_data(),
	.info_rf_TestRAM_addr(),
	.info_rf_TestRAM_ren(),
	.info_rf_TestRAM_rdata(),
	.info_rf_TestRAM_wen(),
	.info_rf_TestRAM_wdata()
);
*/
module ramRF
(
	///\defgroup sys
	///@{ 
	input wire res_n,
	input wire clk,
	///}@ 
	///\defgroup rw_if
	///@{ 
	input wire[7:3] address,
	output reg[63:0] read_data,
	output reg invalid_address,
	output reg access_complete,
	input wire read_en,
	input wire write_en,
	input wire[63:0] write_data,
	///}@ 
	input wire[4:0] info_rf_TestRAM_addr,
	input wire info_rf_TestRAM_ren,
	output wire[15:0] info_rf_TestRAM_rdata,
	input wire info_rf_TestRAM_wen,
	input wire[15:0] info_rf_TestRAM_wdata

);

	reg[4:0] info_rf_TestRAM_rf_addr;
	reg info_rf_TestRAM_rf_ren;
	wire[15:0] info_rf_TestRAM_rf_rdata;
	reg info_rf_TestRAM_rf_wen;
	reg[15:0] info_rf_TestRAM_rf_wdata;
	reg read_en_dly0;
	reg read_en_dly1;
	reg read_en_dly2;

	ram_2rw_1c #(
		.DATASIZE(16),
		.ADDRSIZE(5),
		.PIPELINED(0)
	) info_rf_TestRAM (
		.clk(clk),
		.wen_a(info_rf_TestRAM_rf_wen),
		.ren_a(info_rf_TestRAM_rf_ren),
		.addr_a(info_rf_TestRAM_rf_addr),
		.wdata_a(info_rf_TestRAM_rf_wdata),
		.rdata_a(info_rf_TestRAM_rf_rdata),
		.wen_b(info_rf_TestRAM_wen),
		.ren_b(info_rf_TestRAM_ren),
		.addr_b(info_rf_TestRAM_addr),
		.wdata_b(info_rf_TestRAM_wdata),
		.rdata_b(info_rf_TestRAM_rdata)
	);


	/* RamBlock info_rf_TestRAM */
	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			`ifdef ASIC
			info_rf_TestRAM_rf_addr <= 5'b0;
			info_rf_TestRAM_rf_wdata  <= 16'b0;
			`endif
			info_rf_TestRAM_rf_wen <= 1'b0;
			info_rf_TestRAM_rf_ren <= 1'b0;
		end
		else
		begin
			if (address[7:8] == 0)
			begin
				info_rf_TestRAM_rf_addr <= address[7:3];
				info_rf_TestRAM_rf_wdata <= write_data[15:0];
				info_rf_TestRAM_rf_wen <= write_en;
				info_rf_TestRAM_rf_ren <= read_en;
			end
		end
	end


	`ifdef ASYNC_RES
	always @(posedge clk or negedge res_n) `else
	always @(posedge clk) `endif
	begin
		if (!res_n)
		begin
			invalid_address <= 1'b0;
			access_complete <= 1'b0;
			`ifdef ASIC
			read_data   <= 64'b0;
			`endif

			read_en_dly0 <= 1'b0;
			read_en_dly1 <= 1'b0;
			read_en_dly2 <= 1'b0;
		end
		else
		begin
			read_en_dly0 <= read_en;
			read_en_dly1 <= read_en_dly0;
			read_en_dly2 <= read_en_dly1;

			casex(address[7:3])
				{0'h0,5'bxxxxx}:
				begin
					read_data[15:0] <= info_rf_TestRAM_rf_rdata;
					read_data[63:16] <= 48'b0;
					invalid_address <= 1'b0;
					access_complete <= write_en || read_en_dly2;
				end
				default:
				begin
					invalid_address <= read_en || write_en;
					access_complete <= read_en || write_en;
				end		
			endcase
		end
	end
endmodule